//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInCSharp1.Dialogue.Class_Info {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarriorInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarriorInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameInCSharp1.Dialogue.Class_Info.WarriorInfo", typeof(WarriorInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His max health is 150, the highest of all of the classes..
        /// </summary>
        internal static string WarriorHealthInfo {
            get {
                return ResourceManager.GetString("WarriorHealthInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warrior is strong, able to withstand numerous injuries..
        /// </summary>
        internal static string WarriorInfo {
            get {
                return ResourceManager.GetString("WarriorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He is also hard-hitting, but lacks on the magical spectrum of the world..
        /// </summary>
        internal static string WarriorInfo2 {
            get {
                return ResourceManager.GetString("WarriorInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His max mana is a mere 50..
        /// </summary>
        internal static string WarriorManaInfo {
            get {
                return ResourceManager.GetString("WarriorManaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to His max stamina is 100..
        /// </summary>
        internal static string WarriorStaminaInfo {
            get {
                return ResourceManager.GetString("WarriorStaminaInfo", resourceCulture);
            }
        }
    }
}
