//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInCSharp1.Scripts.Battle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BattleText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BattleText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameInCSharp1.Scripts.Battle.BattleText", typeof(BattleText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Attack.
        /// </summary>
        internal static string attackLabel {
            get {
                return ResourceManager.GetString("attackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do an attack!.
        /// </summary>
        internal static string DoAnAttack {
            get {
                return ResourceManager.GetString("DoAnAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been encountered by {0}!.
        /// </summary>
        internal static string EngagedInCombat {
            get {
                return ResourceManager.GetString("EngagedInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s health is {1}.
        /// </summary>
        internal static string monsterHealth {
            get {
                return ResourceManager.GetString("monsterHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Rest.
        /// </summary>
        internal static string restLabel {
            get {
                return ResourceManager.GetString("restLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Heal.
        /// </summary>
        internal static string specialLabel {
            get {
                return ResourceManager.GetString("specialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Health is {0}/{1}.
        /// </summary>
        internal static string yourHealth {
            get {
                return ResourceManager.GetString("yourHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mana is {0}/{1}.
        /// </summary>
        internal static string yourMana {
            get {
                return ResourceManager.GetString("yourMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Stamina is {0}/{1}.
        /// </summary>
        internal static string yourStamina {
            get {
                return ResourceManager.GetString("yourStamina", resourceCulture);
            }
        }
    }
}
