//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInCSharp1.Dialogue {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TutorialDialogue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TutorialDialogue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameInCSharp1.Dialogue.TutorialDialogue", typeof(TutorialDialogue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Edna&gt; I am Edna. A witch. What are you?.
        /// </summary>
        public static string ClassAsking {
            get {
                return ResourceManager.GetString("ClassAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Edna&gt; Come with me, wont you? I did save your life, afterall..
        /// </summary>
        public static string GameStart1 {
            get {
                return ResourceManager.GetString("GameStart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And now we need to save something else....
        /// </summary>
        public static string GameStart2 {
            get {
                return ResourceManager.GetString("GameStart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The World..
        /// </summary>
        public static string GameStart3 {
            get {
                return ResourceManager.GetString("GameStart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt; Hello. Welcome to the world of [PH]Narnia..
        /// </summary>
        public static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt; Hello, {0}..
        /// </summary>
        public static string HelloName {
            get {
                return ResourceManager.GetString("HelloName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt; May I have your name?.
        /// </summary>
        public static string NameAsking {
            get {
                return ResourceManager.GetString("NameAsking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Unknown&gt; Enter your name: .
        /// </summary>
        public static string NameAskingPrompt {
            get {
                return ResourceManager.GetString("NameAskingPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Edna&gt; A {0}, huh? Fascinating. I have never seen one in my long life..
        /// </summary>
        public static string SmallTalk1 {
            get {
                return ResourceManager.GetString("SmallTalk1", resourceCulture);
            }
        }
    }
}
